### ISSUE TITLE
Remove custom-typings.d.ts

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular/angular2-seed#100]
I think it was temporary and it is about good time to remove `custom-typings.d.ts`. @gdi2290 do you agree?

**Comment by gdi2290** [comment]
The alias legacy import/exports should be removed but the file should stay. The file is only there to help new users who need a place to keep their custom-typings. With TypeScript 2.0 this file will be more necessary with new declare module syntax `declare module "*"`/`declare module "*.html"`. Another example of a completely unneeded file but is needed for new users is vendor. Technically it's better to define these imports within webpack but the separation allows for new ts/ng2 devs a spot to place their vendor 3rd party modules. These two files provide a familiar workflow for devs who are used to the including script tag or the correct `angular.module` name

**Comment by pkozlowski-opensource** [comment]
Makes sense, will amend my PR. Could you PTAL on the others PRs in the meantime?

**Comment by pkozlowski-opensource** [comment]
Fixed in 6b43b10a3288d919cad5971246aaf2c7e3c9cde6
