### ISSUE TITLE
Question: main idea behind the WebPack config split?

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular/angular2-seed#108]
@gdi2290 currently in our `webpack.config.js` we've got 2 config blogs that get merged later on:
- `webpackConfig`
- `defaultConfig`

It is not immediately clear for me why this split exists and what is the added value of it. Could we potentially get rid of this split? Or are you seeing this as something essential?

**Comment by gdi2290** [comment]
resolve.extensions, node and output.filename can be moved up and you can remove the webpack-merge
