### ISSUE TITLE
npm run build problem

### ISSUE THREAD

**Issue by istiti** [angular/angular2-seed#110]
when I did npm run build all my .js files go to /dist ... but there are no index.html and css style in separated file.

I see there is issue for this but this is not solved or my english is poor can someone respond me why the build isn't make in good way

and my output file vendors .js  is more than 2mb is this normal I donot have a big app just this seed repo, I don't understand why it's so big :(

**Comment by pkozlowski-opensource** [comment]
Sorry, it is not clear at all what your problem is nor how anyone could help you....
