### ISSUE TITLE
errors after using npm start

### ISSUE THREAD

**Issue by Miss-Git** [angular/angular2-seed#111]
I'm having the following errors;

SyntaxError: Unexpected token var
    at Object.exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at module.exports (C:\Users\Sulmaz\Desktop\Life\UI & UX\Codes\angular2-seed-master\node_modules\webpack\bin\convert-argv.js:80:13)
    at Object.<anonymous> (C:\Users\Sulmaz\Desktop\Life\UI & UX\Codes\angular2-seed-master\node_modules\webpack-dev-server\bin\webpack-dev-server.js:55:48)

npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "server"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE
npm ERR! angular2-seed@1.0.0 server: `webpack-dev-server --inline --colors --progress --display-error-details --display-cached --port 3000  --content-base src`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-seed@1.0.0 server script 'webpack-dev-server --inline --colors --progress --display-error-details --display-cached --port 3000  --content-base src'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --inline --colors --progress --display-error-details --display-cached --port 3000  --content-base src
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-seed
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-seed
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Sulmaz\Desktop\Life\UI & UX\Codes\angular2-seed-master\npm-debug.log

npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE
npm ERR! angular2-seed@1.0.0 start: `npm run server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-seed@1.0.0 start script 'npm run server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-seed
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-seed
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Sulmaz\Desktop\Life\UI & UX\Codes\angular2-seed-master\npm-debug.log

what should I do?

**Comment by pkozlowski-opensource** [comment]
> what should I do?

I'm sorry but I don't know. There is just not enough info here so we could help in any meaningful way....
