### ISSUE TITLE
Where are the built files written to?

### ISSUE THREAD

**Issue by dopatraman** [angular/angular2-seed#113]
I'm looking at the webpack.config file and I see this block:
```
output: {
    path: './dist',
  },
```

However, when I build the project with `npm start`, although I am able to load the project in the browser I cannot find the `dist` directory. Where are the built files being written?

**Comment by gcollomb** [comment]
Same for me. I work with Win7. How to set in Production ?

**Comment by willyelm** [comment]
If you run `npm start` in the project it will use webpack-dev-server, and all files server by it will by ran from the memory, so there will be no files created on the disk.

You can resolve it by using `npm run watch` and then server the files somewhere else.

**Comment by pkozlowski-opensource** [comment]
@willyelm explanation covers what is going on during dev. For prod build see #17
