### ISSUE TITLE
Need to load template/templateUrl dynamically 

### ISSUE THREAD

**Issue by ravindra1436** [angular/angular2-seed#114]
Hi,
I want to load template/TemplateUrl dynamically. like below,

@Component({
selector:'my-app',
templateUrl: GetTemplate()
})

or

@Component({
selector:'my-app',
template: GetTemplateHtml()
})

export class MyAppComponent{

GetTemplateHtml(){
return './app.component.html' // This will fetch drom services.
}
}

Some thing like that.
Please help
Thanks in advance

**Comment by pkozlowski-opensource** [comment]
This is not supported in the Angular 2 itself so obviously can't be demonstrated here.
