### ISSUE TITLE
Help with adding github/fetch polyfill to this seed project?

### ISSUE THREAD

**Issue by cquillen2003** [angular/angular2-seed#129]
Can someone help me add the github/fetch polyfill to this project's webpack.config.js file?

The github/fetch docs specify the following: 

`entry: ['whatwg-fetch', ...]`

How does that translate to this project's webpack.config.js entry?  Any help with this would be greatly appreciated.

**Comment by pkozlowski-opensource** [comment]
Please ask support questions on SO: http://stackoverflow.com/questions/tagged/angular2
