### ISSUE TITLE
experimental support for decorators is a feature that is subject to change in a future release

### ISSUE THREAD

**Issue by elmoromourad** [angular/angular2-seed#133]
I just followed the steps in README, but i got this error behind class (components) in visual studio code : 
[ts] Experimental support for decorators is a feature that is subject to change in a future release.
Set the 'Exxperimentaldecorators' option to remove this warning.

**Comment by joshterrill** [comment]
I believe that's just a compiler issue. You can set expiermintalDecorators to true in your `tsconfig.json` file.

**Comment by pkozlowski-opensource** [comment]
Our tsconfig shows proper configuration: https://github.com/angular/angular2-seed/blob/master/tsconfig.json#L9

Thnx for helping out with issues @joshterrill

**Comment by elmoromourad** [comment]
It's already true. tsconfig.json of my project looks like the same in the URL.
