### ISSUE TITLE
Problem with starting npm - webpack: bundle is now VALID.

### ISSUE THREAD

**Issue by radzik07** [angular/angular2-seed#137]
I have a problem with starting npm.
What I do:
1. Put latest release to /Applications/AMPPS/www/angular/admin/
2. npm install
3. npm start
After a while a "webpack: bundle is now VALID".
Stays like this forever.
OS: Mac Sierra
NPM 3.8.6
NODE 5.12.0

**Comment by styopdev** [comment]
Hi @radzik07, I also see this message in my console. I havent experience working with webpack but I guess its not an error message, just a notification that everything is ok with webpack.

**Comment by gdi2290** [comment]
this is webpack telling you the bundle is valid and you should go to localhost:3000
