### ISSUE TITLE
Exit 1 when running the seed project - webpack-dev-server failure

### ISSUE THREAD

**Issue by bostonmacosx** [angular/angular2-seed#143]
So I followed the clone and install instructions for the front page. When I do the npm start I get 

> kynorair:angular2-seed herbstzu$ sudo npm start
> 
> > angular2-seed@1.0.0 start /Users/XX/Desktop/ANGULAR_TESTING/angular2-seed
> > npm run server
> 
> 
> > angular2-seed@1.0.0 server /Users/XX/Desktop/ANGULAR_TESTING/angular2-seed
> > webpack-dev-server --inline --colors --progress --display-error-details --display-cached --port 8080  --content-base src
> 
>  57% 8/10 build modulesError: listen EADDRNOTAVAIL 136.167.24.205:8080
>     at Object.exports._errnoException (util.js:1026:11)
>     at exports._exceptionWithHostPort (util.js:1049:20)
>     at Server._listen2 (net.js:1244:19)
>     at listen (net.js:1293:10)
>     at net.js:1403:9
>     at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:62:16)
>     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:81:10)
> 
> npm ERR! Darwin 15.5.0
> npm ERR! argv "/usr/local/Cellar/node/6.8.0/bin/node" "/usr/local/bin/npm" "run" "server"
> npm ERR! node v6.8.0
> npm ERR! npm  v3.10.9
> npm ERR! code ELIFECYCLE
> npm ERR! angular2-seed@1.0.0 server: `webpack-dev-server --inline --colors --progress --display-error-details --display-cached --port 8080  --content-base src`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the angular2-seed@1.0.0 server script 'webpack-dev-server --inline --colors --progress --display-error-details --display-cached --port 8080  --content-base src'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the angular2-seed package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     webpack-dev-server --inline --colors --progress --display-error-details --display-cached --port 8080  --content-base src
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs angular2-seed
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls angular2-seed
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /Users/XX/Desktop/ANGULAR_TESTING/angular2-seed/npm-debug.log
> 
> npm ERR! Darwin 15.5.0
> npm ERR! argv "/usr/local/Cellar/node/6.8.0/bin/node" "/usr/local/bin/npm" "start"
> npm ERR! node v6.8.0
> npm ERR! npm  v3.10.9
> npm ERR! code ELIFECYCLE
> npm ERR! angular2-seed@1.0.0 start: `npm run server`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the angular2-seed@1.0.0 start script 'npm run server'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the angular2-seed package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     npm run server
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs angular2-seed
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls angular2-seed
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /Users/XX/Desktop/ANGULAR_TESTING/angular2-seed/npm-debug.log

**Comment by gdi2290** [comment]
your port 8080 is taken
