### ISSUE TITLE
There are two target. remove line 5

### ISSUE THREAD

**Issue by yoni386** [angular/angular2-seed#144]
**"target": "es5",**
    "module": "commonjs",
    **"target": "es5",**

**Comment by gdi2290** [comment]
@yoni386 can you make a PR?

**Comment by yoni386** [comment]
Sorry but what do you mean by PR?

**Comment by gdi2290** [comment]
it's alright I removed it. thanks!
https://github.com/angular/angular2-seed/commit/659769a5395282b674bf4bd612d5e49e97ef2ebb
