### ISSUE TITLE
error when i start npm

### ISSUE THREAD

**Issue by aymenHarbaoui** [angular/angular2-seed#157]
I get this error below when i start my server npm. Any help ?

ERROR in (webpack)-dev-server/client?http://localhost:8000
Module not found: Error: Can't resolve 'strip-ansi' in 'C:\Angular2\angularSeed\angular2-seed\node_modules\webpack-dev-server\client'
 @ (webpack)-dev-server/client?http://localhost:8000 3:16-37
 @ multi main

ERROR in (webpack)-dev-server/client/socket.js
Module not found: Error: Can't resolve 'sockjs-client' in 'C:\Angular2\angularSeed\angular2-seed\node_modules\webpack-dev-server\client'
 @ (webpack)-dev-server/client/socket.js 1:13-37
 @ (webpack)-dev-server/client?http://localhost:8000
 @ multi main
webpack: bundle is now VALID.

**Comment by peturh** [comment]
Are you sure your using the correct node version? I got the same when I was using Node 4.x

**Comment by aymenHarbaoui** [comment]
i have npm@2.15.8  version  and node 4.x

**Comment by peturh** [comment]
Then there is your problem. 

From README.md:

> Make sure you have node.js installed version 5+

**Comment by aymenHarbaoui** [comment]
Okay thank you  ! because i used npm in different project ( as cordova mobile)  so i think as you said this my probleme. Thank you very much
