### ISSUE TITLE
Use source maps or bundle prod build

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular/angular2-seed#19]
Today we are pulling dev build of ng2 with in-lined source maps but since we don't have source maps plugins setup properly on WebPack side, those source maps are not available for end users. 

So, we've got a situation where we pay a price (size) of source maps but can't benefit. We need to do one of the 2:
* properly configure source maps plugin on the WebPack side, or
* use prod input of ng2 for bundling

**Comment by robwormald** [comment]
can we solve the sourcemap problem upstream on angular2? we should really have `.js`, `.map.js` and `.d.ts` being distributed to npm. anything else is gonna require a bunch of configuration for end users.

**Comment by pkozlowski-opensource** [comment]
> can we solve the sourcemap problem upstream on angular2?

by publishing prod instead of dev to the root ?

**Comment by robwormald** [comment]
i think that's probably the best solution long term.

**Comment by pkozlowski-opensource** [comment]
So, was trying to see what we can do on this repo side (till the decision is made in the main repo) with:

```
preLoaders: [
      {test: /\.js$/, loader: 'source-map-loader'}
]
```

but getting flooded with:

> WARNING in ./~/rxjs/Observable.js
Cannot find source file '../../src/Observable.ts': Error: Cannot resolve 'file' or 'directory' ../../src/Observable.ts in /home/pk/work/gitrepos/gh/pkozlowski-opensource/angular2-seed/node_modules/rxjs

> WARNING in ./~/rxjs/Subject.js
Cannot find source file '../../src/Subject.ts': Error: Cannot resolve 'file' or 'directory' ../../src/Subject.ts in /home/pk/work/gitrepos/gh/pkozlowski-opensource/angular2-seed/node_modules/rxjs

> WARNING in ./~/rxjs/add/operator/map.js
Cannot find source file '../../../../src/add/operator/map.ts': Error: Cannot resolve 'file' or 'directory' ../../../../src/add/operator/map.ts in /home/pk/work/gitrepos/gh/pkozlowski-opensource/angular2-seed/node_modules/rxjs/add/operator

It looks like source maps might be off in the rxjs repo

**Comment by pkozlowski-opensource** [comment]
Sth to be fixed on the RxJS side: https://github.com/ReactiveX/RxJS/issues/1089

**Comment by trodrigues** [comment]
Wouldn't this problem be fixed if you told the webpack config not to ignore node_modules/angular2 and if you turned on sourcemaps on the tsconfig.json for development (and also told it not to exclude all of node_modules as is the case right now)?

Then you'd get sourcemaps for the development setup, and for the production setup you could just use the same sources but turn off sourcemaps.

**Comment by johnwheeler** [comment]
Hello, I was wondering if there is yet a way to shrink the vendor.bundle.js size? I added

**Comment by gdi2290** [comment]
@johnwheeler I added the source-map-loader to correctly map the inline source maps provided by angular2 which cut the vendor size in half. The build time is slower because we have to deal with the inline source maps. I also have to exclude rxjs and angular2-material until their source maps are fixed. closing for now
