### ISSUE TITLE
Load angular2-polyfills via a script tag

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular/angular2-seed#27]
See https://github.com/angular/angular/blob/master/modules/angular2/docs/bundles/overview.md#required-polyfills and grief it causes otherwise: https://github.com/angular/angular/issues/5980

**Comment by gdi2290** [comment]
I created a polyfill/vendor/application chunks to allow the developer to determine where the code should live. The developer may want to include other polyfills in which case they need to know what polyfills are always being used. The developer may want to go to production and does not want to bundle `long-stack-trace-zone` with their app
