### ISSUE TITLE
Webpack noparse config is incorrect

### ISSUE THREAD

**Issue by starjumper30** [angular/angular2-seed#29]
The current webpack config causes warning messages about angular-polyfills.js. 

The warnings disappear if you change it to:
noParse: [ path.join(__dirname, "node_modules", "angular2", "bundles")]

(I'm not submitting a pull request because I am not a git user.)

**Comment by gdi2290** [comment]
@starjumper30 can you change it to `/.+angular2\/bundles\/.+/` and see if that works for you

**Comment by starjumper30** [comment]
Tried that, still get the warnings. I just downloaded this seed project half an hour ago, did npm install and then npm start, so there shouldn't be anything weird about my setup. Works fine if I change it to a path instead of a regular expression.

**Comment by robwormald** [comment]
@gdi2290 you broke it, you fix it.

**Comment by gdi2290** [comment]
#openSourceLife
