### ISSUE TITLE
Routing  when refresh the page, return 404

### ISSUE THREAD

**Issue by liu-kanghui** [angular/angular2-seed#35]
import {bootstrap} from 'angular2/platform/browser';
import {HTTP_PROVIDERS} from 'angular2/http';
import {
	ROUTER_PROVIDERS,
	HashLocationStrategy,
	LocationStrategy
} from 'angular2/router';
import {provide} from 'angular2/core';
import {SeedApp} from './app/seed-app';

bootstrap(SeedApp,[
	HTTP_PROVIDERS, 
	ROUTER_PROVIDERS,
	provide(LocationStrategy, {useClass: HashLocationStrategy})
]).catch(err => console.error(err));

the default strategy works with hash based paths. so we need to use HashLocationStrategy instead of  PathLocationStrategy.

**Comment by deepakgd** [comment]
For me redirecting to home page. how to fix this?

**Comment by gdi2290** [comment]
Thanks for opening an issue. done via https://github.com/angular/angular2-seed/commit/58bec8f65bcaba924978b2fe4a8cb398bc0b3d1c
