### ISSUE TITLE
webpack creates two files in .dist

### ISSUE THREAD

**Issue by iBasit** [angular/angular2-seed#37]
My application was throwing file cant find, for two included files which webpack makes. 

index.html has it on same folder, but webpack makes it on .dist/ folder. 

Is this mistake or I have to do something else to have this working correctly?

**Comment by gdi2290** [comment]
`webpack-dev-server` is serving `src/` while the `dist/` is built and served in-memory. If you were going to use another server then you would have to copy over the index.html as well as any other static content (including the template files). Don't open the `index.html` file directly in the browser. Please use `webpack-dev-server` or update the config to copy over the files
