### ISSUE TITLE
Change the structure to follow the anguar2-style-guide

### ISSUE THREAD

**Issue by evanplaice** [angular/angular2-seed#38]
Ref: https://github.com/mgechev/angular2-style-guide

We're still [fleshing out some of the details](https://github.com/mgechev/angular2-style-guide/issues/5) surrounding directory structure but here's the gist:
- use `app` (ie not src) as the base folder of the angular2 application
  
  This is what the [angular-cli](https://github.com/angular/angular-cli) as well as many other existing seed/boilerplate projects currently use.
- change from by-type to a by-feature structure
  
  This is a fundamental departure from the patterns used in AngularJS but it's essential to maximize module reuse. [angular-cli](https://github.com/angular/angular-cli) also follows this pattern.
- consolidate the repo components and service under a single feature
  
  To follow more of a DDD approach.

**Comment by gdi2290** [comment]
@evanplaice can you make a PR?

**Comment by pkozlowski-opensource** [comment]
@gdi2290 I know that @IgorMinar has a detailed proposal for dir structure to be generated / used by the CLI so the 2 should be aligned.

**Comment by francescopersico** [comment]
https://angular.io/styleguide This is the correct link for styleguide. This repo is not lined-up with the official styleguide.

Example:
Do put bootstrapping and platform logic for the app in a file named main.ts.

**Comment by evanplaice** [comment]
@francescopersico When this issue was created, the official style guide didn't exist

Things will be adjust as 'best practices' solidify.
