### ISSUE TITLE
Run 'npm start' error

### ISSUE THREAD

**Issue by ldzhu** [angular/angular2-seed#41]
`ERROR in D:\angular2\angular2-seed\node_modules\angular2\src\facade\promise.d.ts
(1,10): error TS2661: Cannot re-export name that is not defined in the module.`

**Comment by tindecken** [comment]
same issue
`https://i.imgur.com/K2o3fdd.jpg`

**Comment by Kelderic** [comment]
Getting the exact same error. Can't start up the server.

**Comment by leesolway** [comment]
Same issue.

**Comment by Evgen1000end** [comment]
Same issue.

**Comment by gambtho** [comment]
This seems to be a known issue with that version of typescript -- i submitted a pull request that fixes it, but you can manually upgrade 

 npm install --save rxjs@5.0.0-beta.2 zone.js@0.5.15 angular@2.0.0-beta.8

and add this line to the top of app.ts (you need to keep the /// )
/// <reference path="../node_modules/angular2/typings/browser.d.ts" />

**Comment by gdi2290** [comment]
Thanks for opening an issue the repo has been redone with the correct types. Please pull latest changes
