### ISSUE TITLE
Bower component: May i know how to link bower component in angular2 app

### ISSUE THREAD

**Issue by deepakgd** [angular/angular2-seed#42]
Bower component: May i know how to link bower component in angular2 app 1. bower install bootstrap 2. index.html

```
<script src="bower_components/jquery/dist/jquery.js"></script>
<link rel="stylesheet" href="bower_components/bootstrap/dist/css/bootstrap.css">
```

I am getting 404 issue

**Comment by gdi2290** [comment]
use npm 3 over bower

**Comment by deepakgd** [comment]
Npm3 is slow so that I m using bower component

**Comment by maxmumford** [comment]
Can we reopen this issue? Sometimes packages are available only on bower and not npm.

**Comment by pkozlowski-opensource** [comment]
> Can we reopen this issue? Sometimes packages are available only on bower and not npm.

Then convince authors to deploy to npm. Sorry, we've got no intention of supporting bower.
