### ISSUE TITLE
Run "npm start" error: "Cannot resolve module 'process'"

### ISSUE THREAD

**Issue by KostyaTretyak** [angular/angular2-seed#51]
I have npm v2.14.20, node v5.8.0, and when `npm srart` throw many errors with `Cannot resolve module 'process'`:
```
ERROR in (webpack)-dev-server/~/sockjs-client/lib/main.js
Module not found: Error: Cannot resolve module 'process' in /var/www/angular2-seed/node_modules/webpack-dev-server/node_modules/sockjs-client/lib
 @ (webpack)-dev-server/~/sockjs-client/lib/main.js 1:0-18
...
```

When I removed `process: 1` from `webpack.config.js`
```javascript
// ...
  node: {
    global: 1,
    process: 1,
    crypto: 'empty',
    module: 0,
    Buffer: 0,
    clearImmediate: 0,
    setImmediate: 0
  },
// ...
```

start OK, but in Google Chrome error:
```
Uncaught (in promise) TypeError: object is not a constructor
    at then (native)
```

**Comment by manekinekko** [comment]
@KostyaTretyak I can't reproduce your issue. The app bootsraps fine here. Could you try a clean install?

**Comment by KostyaTretyak** [comment]
Now already removed `process: 1`  (https://github.com/angular/angular2-seed/commit/a5d2f204fb1a068d7b9144e0f6c14d07e0e94f4a)

But still
```
Uncaught (in promise) TypeError: object is not a constructor
    at then (native)
```

**Comment by TimAnstee** [comment]
I think this is related to the --inline flag or something in that area.  Removing the flag makes the thing run again. Webpack is still a bit of a mystery to me, but it looks like it may be related to this.

**Comment by KostyaTretyak** [comment]
I remove my `nvm`, reinstall `nodejs` (v4.4.0) and angular2-seed work without errors.

Sorry that your time spent on this issue.
