### ISSUE TITLE
Include Dockerfile

### ISSUE THREAD

**Issue by colemickens** [angular/angular2-seed#56]
I've tried this a few times and every time I run into some random problem that I can only assume is related to the version of node/npm installed or something. A Dockerfile would help alleviate this.

**Comment by gdi2290** [comment]
@colemickens can you make a pull-request?

**Comment by robertBrem** [comment]
I don't know the condition for a pull request. But I have a starting point for you. It is working for me:
```
FROM node:slim

MAINTAINER Robert Brem <brem_robert@hotmail.com>

RUN apt-get update && \
    apt-get install git -y
WORKDIR /var/www
RUN git clone https://github.com/robertBrem/pokerui
WORKDIR /var/www/pokerui
RUN apt-get purge -y git && \
    apt-get autoremove -y && \
    apt-get -y clean && \
    rm -rf /var/lib/apt/lists/*

RUN npm install -g webpack webpack-dev-server typings typescript
RUN npm install
RUN npm run typings-install  
RUN typings install 
CMD npm start
```
I had also to add the `-- host 0.0.0.0` in `package.json`. But i think normally it should be the default.
```
    "server": "webpack-dev-server --inline --colors --progress --display-error-details --display-cached --host 0.0.0.0 --port 3000 --content-base src",
```

**Comment by pkozlowski-opensource** [comment]
I think it is out of scope of this simple starter kit. Closing for now.
