### ISSUE TITLE
EXCEPTION: UnsubscriptionError

### ISSUE THREAD

**Issue by nandel** [angular/angular2-seed#57]
I'm getting the follow exception when i run the seed:

i get that on: http://localhost:3000/#/github/angular

I wonder if the error is on seed itself, baucase a2 changed the behavior.
[localhost-1459890742639.txt](https://github.com/angular/angular2-seed/files/205351/localhost-1459890742639.txt)

**Comment by barocsi** [comment]
+1

**Comment by bautistaaa** [comment]
i get the same error in addition to this error as well

[default] /Users/chrisbautista/workspace/angular2-seed/src/polyfills.ts:11:0 
Cannot find name 'require'.

thoughts?

**Comment by bautistaaa** [comment]
+1

are you guys getting duplicate identifier errors as well?

angular2-seed/typings/browser/ambient/es6-promise/index.d.ts:45:15 
Duplicate identifier 'Promise'.

angular2-seed/typings/browser/ambient/es6-promise/index.d.ts:50:33 
Generic type 'Thenable<T, R>' requires 2 type argument(s).

**Comment by pkozlowski-opensource** [comment]
Sounds like an obsolete support request. Closing.
