### ISSUE TITLE
Add new files, such as css and stuff

### ISSUE THREAD

**Issue by peturh** [angular/angular2-seed#58]
I've used `webpack` before in another project. Never used` webpack-dev-server` though. 

I've just added [material-design lite](https://www.getmdl.io/started/index.html#download) through NPM.

In my earlier webpack projects, I included all the files I wanted through adding 

`var mdl = require('node_modules/material ...' ) `etc. 

Where are all the files included here? Am I missing something? What module are including the `.ts, .html and .css `files in the component folders?

An example for adding for example this package or for example lodash would be great.

**Comment by giacomocerquone** [comment]
I'm starting right now with webpack and it seems rocket science.
I'm searching a clean way to add a css library (like animate.css for example), what would that be?
Hoping for answers, thank you!

**Comment by RicardoVaranda** [comment]
Easiest way to get an app up and running is to use Angular CLI, it does not use webpack but instead systemJS. Adding new files whether it be css or js files is a very straight forward process of around 2 or 3 steps.

**Comment by giacomocerquone** [comment]
@RicardoVaranda thank you for your advice.
Two things are disturbing me right now.
1. That cli utility is a huge thing... I know nothing of its underlying work
2. Could you tell me the proper way of adding css and other assets resources? (I just found this tutorial that explain how to add js libraries https://github.com/angular/angular-cli/wiki/3rd-party-libs but nothing on css)

**Comment by RicardoVaranda** [comment]
@giacomocerquone 

## Step1 : 

> ng new Project_Name

## Step2 (may not be required):

> cd Project_Name
> npm run postinstall

## Step 3
Follow this:
https://github.com/angular/angular-cli/wiki/3rd-party-libs#adding-material2-to-your-project
On step 3 instead of:
```
vendorNpmFiles: [
      '@package_name/**/*.js'
    ]
```

run something like this:

```
vendorNpmFiles: [
      '@package_name/**/*.+(js|css)'
    ]
```

The rest will be the same, when including it in your index.html do the following:

`<link rel="stylesheet" href="vendor/ng2-material/dist/ng2-material.css">`

If you give me a specific package you want to install I'll change my description above to match your needs :)

**Comment by pkozlowski-opensource** [comment]
Sounds like a support question, not sure what should be done in this repo. Please keep in mind that the goal of this repository is to have a minimal setup and not something that is going to demonstrate all possible setup options.

**Comment by rafalsobota** [comment]
Does this seed not support images?
