### ISSUE TITLE
RxJS5 - additional operators & TS typings. 

### ISSUE THREAD

**Issue by zachgrayio** [angular/angular2-seed#59]
I've been struggling for awhile with getting the typescript compiler to play nice with operators imported like so: `import 'rxjs/add/operator/distinct'` etc. I've tried importing Rx.Kitchensink and declaring observables via Rx.Observable, and every other suggestion I've come across on the issue trackers with no luck. 

I thought maybe it was just a typings issue, but when trying to install rxjs typings, I noticed that the command `typings install rxjs-symbol-typings` 404s... But honestly I'm not even sure if this is even relevant.

Any thoughts?

**Comment by kwonoj** [comment]
just fyi, 

`typings install rxjs-symbol-typings` isn't required any more from b.6, actually b.5 tried to introduce it but has dropped it. I believe any problem would not be related with those specific typings if you're using b.6 of RxJS.

**Comment by zachgrayio** [comment]
@kwonoj cool, I'll cross that off the list

**Comment by zachgrayio** [comment]
Here's an example - i just forked the repo and followed the most common, basic instructions to import additional operators, with no other changes. Maybe this is a bit too naive, but I thought it was a good starting point: https://github.com/zachgrayio/angular2-seed-add-operators/commit/aa40285f69edf09475c4d206c530e143cba33cd5

**Comment by kwonoj** [comment]
I have updated here https://github.com/ReactiveX/rxjs/issues/1560#issuecomment-210299585 for this issue, basically it requires latest version of `rxjs` package instead of b.2. ng2 tracks to bump up rxjs in https://github.com/angular/angular/pull/8047.

**Comment by zachgrayio** [comment]
Thanks to @kwonoj for the fix.

For anyone who ends up here, this is the commit that fixed my operator woes: https://github.com/zachgrayio/angular2-seed-add-operators/commit/cdd825c2c92de6917dc86f926d23db65f426e1d0

If you run into the peer dependency issue due to being ahead of the peerdependency curve, you can install npm3 with `sudo npm i -g npm@3` and then `npm i` will succeed due to it's new dependency resolution model.
