### ISSUE TITLE
Loading angular dependencies in code or webpack

### ISSUE THREAD

**Issue by Foxandxss** [angular/angular2-seed#6]
I have seen that you load `zone.js` and `reflect-metadata` directly on `app.ts`.

Another way would be add it on the entry point as dependencies or even create your own entry point only  for angular 2 and dependencies.

To be honest, I haven't figured this out yet.

Technically having angular2 / vendors in a separate bundle could make the browser not to download the entire angular 2 when there is an update in the app.

**Comment by pkozlowski-opensource** [comment]
Yeh, I want to have a discussion on this one :-)

**Comment by gdi2290** [comment]
:+1: I agree with the separation between application code and vendor code. 

I updated [`angular2-webpack-starter`](https://github.com/angularclass/angular2-webpack-starter) with a vendor file that seems to make more sense without hiding anything in a webpack config. The recent refactor also allows developers to easily refactor the repo into different environments. (`bootstrap.ts` should really be called `browser.ts` and there should be support for web worker `./src/ui.ts`, `./src/worker`)

* [`./src/vendor.ts`](https://github.com/AngularClass/angular2-webpack-starter/blob/ecfd2e580f54bc90e329da9b0c013c635fbde447/src/vendor.ts)
* [`./src/bootstrap.ts`](https://github.com/AngularClass/angular2-webpack-starter/blob/ecfd2e580f54bc90e329da9b0c013c635fbde447/src/bootstrap.ts)
* [`./webpack.config`](https://github.com/AngularClass/angular2-webpack-starter/blob/ecfd2e580f54bc90e329da9b0c013c635fbde447/webpack.config.js#L21...L24)

you can also just require `./src/vendor.ts` from `./src/bootstrap.ts`.
