### ISSUE TITLE
'angular' is not in the npm registry.

### ISSUE THREAD

**Issue by ambarox** [angular/angular2-seed#72]
npm WARN package.json angular2-seed@1.0.0 scripts['server'] should probably be scripts['start'].
npm http GET http://registry.npmjs.org/angular/http/2.0.0-rc.1
npm http GET http://registry.npmjs.org/angular/compiler/2.0.0-rc.1
npm http GET http://registry.npmjs.org/angular/core/2.0.0-rc.1
npm http GET http://registry.npmjs.org/angular/platform-browser/2.0.0-rc.1
npm http GET http://registry.npmjs.org/angular/platform-browser-dynamic/2.0.0-rc.1
npm http GET http://registry.npmjs.org/angular/common/2.0.0-rc.1
npm http GET http://registry.npmjs.org/angular/platform-server/2.0.0-rc.1
npm http GET http://registry.npmjs.org/angular/router/2.0.0-rc.1
npm http GET http://registry.npmjs.org/angular/router-deprecated/2.0.0-rc.1
npm http GET http://registry.npmjs.org/core-js
npm http GET http://registry.npmjs.org/es6-promise/3.0.2
npm http GET http://registry.npmjs.org/es6-shim/0.35.0
npm http GET http://registry.npmjs.org/source-map-loader
npm http GET http://registry.npmjs.org/awesome-typescript-loader
npm http GET http://registry.npmjs.org/typescript
npm http GET http://registry.npmjs.org/typings
npm http GET http://registry.npmjs.org/webpack-dev-server
npm http GET http://registry.npmjs.org/webpack-merge
npm http GET http://registry.npmjs.org/webpack
npm http 404 http://registry.npmjs.org/angular/core/2.0.0-rc.1
npm http 404 http://registry.npmjs.org/angular/platform-browser/2.0.0-rc.1
npm ERR! 404 'angular' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 3.19.0-58-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/lasitha/Projects/Trials/angular2-seed
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! code E404
npm http 404 http://registry.npmjs.org/angular/platform-server/2.0.0-rc.1
npm http 404 http://registry.npmjs.org/angular/router/2.0.0-rc.1
npm http 404 http://registry.npmjs.org/angular/http/2.0.0-rc.1
npm http 404 http://registry.npmjs.org/angular/compiler/2.0.0-rc.1
npm http 404 http://registry.npmjs.org/angular/platform-browser-dynamic/2.0.0-rc.1
npm http 404 http://registry.npmjs.org/angular/router-deprecated/2.0.0-rc.1
npm http 304 http://registry.npmjs.org/core-js
npm http 404 http://registry.npmjs.org/angular/common/2.0.0-rc.1
npm http 304 http://registry.npmjs.org/es6-shim/0.35.0
npm http 304 http://registry.npmjs.org/typescript
npm http 304 http://registry.npmjs.org/typings
npm http 304 http://registry.npmjs.org/es6-promise/3.0.2
npm http 304 http://registry.npmjs.org/webpack-dev-server
npm http 304 http://registry.npmjs.org/source-map-loader
npm http 304 http://registry.npmjs.org/webpack-merge
npm http 304 http://registry.npmjs.org/awesome-typescript-loader
npm http 304 http://registry.npmjs.org/webpack
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/lasitha/Projects/Trials/angular2-seed/npm-debug.log
npm ERR! not ok code 0

**Comment by gdi2290** [comment]
can you update npm and node

**Comment by pkozlowski-opensource** [comment]
`@angular` is definitively well published to npm, sounds like an env specific problem.
