### ISSUE TITLE
Typescript compiler can't resolve my interfaces

### ISSUE THREAD

**Issue by ProGM** [angular/angular2-seed#73]
I recently switched from `SystemJS` + `tsc` to a webpack based configuration (like this repo).

Everything works fine, except I receive a lot of errors on my interfaces:

```bash
ERROR in [default] /Users/me/myproject/app/models/User.ts:12:20
Cannot find name 'UserInterface'.

ERROR in [default] /Users/me/myproject/app/models/file_infos.ts:1:33
Cannot find name 'FileInterface'.

ERROR in [default] /Users/me/myproject/app/models/upload_form.ts:4:29
Cannot find name 'UploadSignature'.

ERROR in [default] /Users/me/myproject/app/models/upload_form.ts:5:17
Cannot find name 'FileInterface'.
...
```

However the generated code runs correctly.

How could I solve? They are located in a `interfaces` folder.

With the previous setup, I didn't have this kind of errors.

**Comment by gdi2290** [comment]
do you have a link to your repo?

**Comment by bbottema** [comment]
I'm having the same issue at work and at home. At home I cleanly installed node and npm as well and followed the instructions to get up and running. I simply forked this repo and didn't change anything.

node: 4.4.4
npm: 3.9.0
typings: 1.0.4

**Comment by pkozlowski-opensource** [comment]
Sounds like a support question without reproduction. Closing for now.
