### ISSUE TITLE
Upgrade to RC2?

### ISSUE THREAD

**Issue by GhdiriAbdallah** [angular/angular2-seed#87]
Is there any plans to upgrade this seed project to RC2 in the near future? Simply changing angular dependency versions from 2.0.0-rc.1 to 2.0.0-rc.2 gives me an UNMET PEER DEPENDENCY error form core and http dependencies.

**Comment by gdi2290** [comment]
thanks, updated to rc.2

**Comment by pkozlowski-opensource** [comment]
@gdi2290 did you push the changes? Master still seem to point to rc.1: https://github.com/angular/angular2-seed/blob/master/package.json#L36-L43

**Comment by GhdiriAbdallah** [comment]
It does not appear so. I think it is wise to upgrade to RC3 directly now.

**Comment by gdi2290** [comment]
I'll update this
