### ISSUE TITLE
Typings install commands

### ISSUE THREAD

**Issue by pokakhoaitay** [angular/angular2-seed#93]
Can anybody please show me how to install the following typings package in `globalDependencies` section:

```json
"globalDependencies": {
    "es6-collections": "registry:dt/es6-collections#0.5.1+20160316155526",
    "es6-promise": "registry:dt/es6-promise#0.0.0+20160423074304",
    "node": "registry:dt/node#4.0.0+20160423143914"
  }
```

Thanks!

**Comment by dixso** [comment]
Hi,
You can install these typings with: `typings install` or if you want install with the command line: `typings install dt~node --global --save`

Regards!

**Comment by pokakhoaitay** [comment]
Thank you! The `typings install dt~node --global --save` is exactly what i need
